-- Fix game_state for multi-game support: remove id=1 constraint, add identity, unique game_id, and robust ensure_game

BEGIN;

-- 1) Drop the legacy CHECK constraint that forced id = 1 (if it exists)
ALTER TABLE game_state DROP CONSTRAINT IF EXISTS game_state_id_check;

-- 2) Ensure id is generated automatically (identity); drop any old default first
ALTER TABLE game_state ALTER COLUMN id DROP DEFAULT;
DO $$
BEGIN
  -- Add identity only if not already identity
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'game_state'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE game_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 3) Ensure we can have one row per game: add a unique constraint on game_id
ALTER TABLE game_state ADD CONSTRAINT IF NOT EXISTS game_state_game_id_key UNIQUE (game_id);

-- 4) Update ensure_game to insert a row for the specific game_id without conflicting on id
CREATE OR REPLACE FUNCTION ensure_game(p_game_id UUID)
RETURNS VOID AS $$
BEGIN
  INSERT INTO game_state (current_round, current_phase, version, created_at, updated_at, game_id)
  VALUES (0, 'Setup', 0, NOW(), NOW(), p_game_id)
  ON CONFLICT (game_id) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

COMMIT;
