-- Retry: Fix game_state for multi-game with unique index instead of constraint

BEGIN;

-- 1) Drop legacy id=1 CHECK if present
ALTER TABLE game_state DROP CONSTRAINT IF EXISTS game_state_id_check;

-- 2) Ensure id auto-generates
ALTER TABLE game_state ALTER COLUMN id DROP DEFAULT;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'game_state' AND column_name = 'id' AND is_identity = 'YES'
  ) THEN
    ALTER TABLE game_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 3) Unique index on game_id (one row per game)
CREATE UNIQUE INDEX IF NOT EXISTS idx_game_state_game_id ON game_state(game_id);

-- 4) Ensure-game upsert by game_id
CREATE OR REPLACE FUNCTION ensure_game(p_game_id UUID)
RETURNS VOID AS $$
BEGIN
  INSERT INTO game_state (current_round, current_phase, version, created_at, updated_at, game_id)
  VALUES (0, 'Setup', 0, NOW(), NOW(), p_game_id)
  ON CONFLICT (game_id) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

COMMIT;
